include ../defs.mk

main8:
	gcc $(CFLAGS) -o ../main8 main8.c -lm -I C:\lapack\include -L ../ -lmolecule \
	-L C:\lapack\bin -L C:\lapack\lib -lcblas -llapacke \
	-llapack -lblas -lgfortran -L../../Free -lmemory