include ../defs.mk

main5:
	gcc $(CFLAGS) -o ../main5 main5.c -lm -I C:\lapack\include -L ../ -lmolecule \
	-L C:\lapack\bin -L C:\lapack\lib -lcblas -llapacke \
	-llapack -lblas -lgfortran -L../../Free -lmemory