include ../defs.mk

main4:
	gcc $(CFLAGS) -o ../main4 main4.c -lm -I C:\lapack\include -L ../ -lmolecule \
	-L C:\lapack\bin -L C:\lapack\lib -lcblas -llapacke \
	-llapack -lblas -lgfortran -L../../Free -lmemory