include ../defs.mk

main2:
	gcc $(CFLAGS) -o ../main2 main2.c -lm -I C:\lapack\include -L ../ -lmolecule \
	-L C:\lapack\bin -L C:\lapack\lib -lcblas -llapacke \
	-llapack -lblas -lgfortran -L../../Free -lmemory