include ../defs.mk

main3:
	gcc $(CFLAGS) -o ../main3 main3.c -lm -I C:\lapack\include -L ../ -lmolecule \
	-L C:\lapack\bin -L C:\lapack\lib -lcblas -llapacke \
	-llapack -lblas -lgfortran -L../../Free -lmemory